/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello from lab08";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        File file = new File("recentquotes.json");
        ArrayList<String> quotes= new ArrayList<String>();
        try {
            JsonElement fileQuote = JsonParser.parseReader(new FileReader(file));
        // get Json array
            JsonArray quotesArray = fileQuote.getAsJsonArray();
        //    System.out.println(quotesArray);


            // convert Json array
            for (JsonElement jsonElement : quotesArray) {

                JsonObject quoteObj = jsonElement.getAsJsonObject();

                JsonArray tagsArr = quoteObj.getAsJsonArray("tags");
               // System.out.println(tagsArr);
                ArrayList<String> tags = new ArrayList<String>();
                for (JsonElement element : tagsArr) {
                  tags.add(element.getAsString()) ;
                }
               // System.out.println(tags);

                String author = quoteObj.get("author").getAsString();
                String likes = quoteObj.get("likes").getAsString();
                String text = quoteObj.get("text").getAsString();

              //  System.out.println(author);
                Quotes quote = new Quotes(tags,author,likes,text);
                quotes.add(quote.toString());
            }
          //  System.out.println("Array list-Json converted : "+quotes);

        }
        catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        randomQuote(quotes);
    }

    public static String randomQuote(ArrayList<String> q){

        System.out.println(q.get((int)Math.random()*q.size()));
        return q.get((int)Math.random()*q.size());
    }
}
